version: '2'
services:
 web:
   build:
     context: ./web/
   working_dir: /var/www/html
   volumes:
    - ./module:/var/www/html
   ports:
    - "80:80"
 database:
   image: 'kartoza/postgis:12.0'
  # volumes:
  #   - postgis-data:/var/lib/postgresql
   ports:
     - "127.0.0.1:5432:5432"
   environment:
     - POSTGRES_DB=unittesting
     - POSTGRES_USER=docker
     - POSTGRES_PASS=docker
     - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology


volumes:
  postgresql_data:
    driver: local
